Clase07 - 11/slnVentas/App.UI.Web.MVC/Controllers/Mantenimientos/CategoriaController.cs
using App.Domain.Services.Interfaces;
using App.Domain.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using App.Entities.Base;
using App.UI.Web.MVC.ModelBinders;

namespace App.UI.Web.MVC.Controllers.Mantenimientos
{
    public class CategoriaController : Controller
    {

        private readonly ICategoriaService categoriaServices;



        public CategoriaController(ICategoriaService pCategoriaServices) {
            categoriaServices = pCategoriaServices;
        }

        // GET: Categoria
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Buscar(string filterByName) {

            filterByName = filterByName != null ? filterByName : "";

            var model = categoriaServices.GetAll(filterByName);

            return PartialView("IndexListado",model);
        }

        public ActionResult Create() {
            return PartialView();
        }

        //[HttpPost]
        //public ActionResult Create( Categoria model )
        //{
        //    var result = categoriaServices.Save(model);

        //    return RedirectToAction("index");            
        //}

        [HttpPost]
        public ActionResult Create(
            [ModelBinder(binderType:typeof(CategoriaBinder))] Categoria model )
        {
            var result = categoriaServices.Save(model);

            return RedirectToAction("index");
        }

        public ActionResult Edit(int id) {

            var model = categoriaServices.GetById(id);

            return View("Create",model);
        }

        [HttpPost]
        public ActionResult Edit(Categoria model)
        {
            var result = categoriaServices.Save(model);
            return RedirectToAction("index");
        }

    }
}

Clase07 - 11/slnVentas/App.UI.Web.MVC/Views/Categoria/Create.cshtml
@model App.Entities.Base.Categoria

@{
    ViewBag.Title = "Create";
    string title = Model == null ? "Crear Categoría" : "Editar Categoría";

}

<h2>@title</h2>

@*Sin HTML Helpers
    <form action="/Categoria/Create" method="post">
        <label>Nombre</label> <input name="nombre" /> <br /><br />
        <label>Descripción</label> <input name="descripcion" /> <br /><br />

        <button class="btn btn-success">Guardar</button>
    </form>*@

@using (Ajax.BeginForm("Create", "Categoria",
    new AjaxOptions() { OnSuccess = "app.CategoriaView.RefreshLista()" }))
{
    <div class="form-horizontal">
        @Html.HiddenFor(model => model.CategoriaID)

        <div class="form-group">
            <label for="inputEmail3" class="col-sm-2 control-label">Nombre</label>
            <div class="col-sm-10">

                @Html.EditorFor(
                    model => model.Nombre,
                    new { htmlAttributes = new { @class = "form-control" } })

                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })

            </div>
        </div>

        <div class="form-group">
            <label for="inputEmail3" class="col-sm-2 control-label">Descripción</label>
            <div class="col-sm-10">
                @Html.EditorFor(
                    model => model.Descripcion,
                    new { htmlAttributes = new { @class = "form-control" } })

                @Html.ValidationMessageFor(model => model.Descripcion)

            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button class="btn btn-success">Guardar</button>
            </div>
        </div>
    </div>

}

Clase07 - 11/slnVentas/App.UI.Web.MVC/Views/Categoria/Index.cshtml
@{
    ViewBag.CurrentPage = "Categoria";
    ViewBag.Title = "Lista de Categorias";
}

<h2>Lista de Categorias</h2>

@*Sin usar Html helpers*@
@*<a href="/Categoria/Create" class="btn btn-success">Nueva Categoría</a>*@

@*Usando HTML Helpers*@

@*@Html.ActionLink("Nueva Categoría","Create","Categoria",new { @class = "btn btn-success" })*@
<div class="row">
    <div class="col-sm-1">        
        <button onclick="app.helpers.showModal('CategoriaCreatePopup','@Url.Action("create")')" class="btn btn-success">Nuevo</button>
    </div>

    @using (Ajax.BeginForm("Buscar", "Categoria",
        new AjaxOptions
        {
            HttpMethod = "POST",
            InsertionMode = InsertionMode.Replace,
            UpdateTargetId = "listado"
        }))
    {
        <div class="row">
            <div class="form-group col-sm-3 ">                
                <input name="filterByName" id="filterByName" class="form-control" placeholder="Buscar por nombre" />
            </div>
            <div class="col-sm-2">                
                <button type="submit" class="buscar btn btn-facebook">Buscar</button>
            </div>
        </div>
    }
</div>

<div id="listado">
    @Html.Action("Buscar")
</div>

@Modal.CrearModal("Crear Categoría", "CategoriaCreatePopup")

@section scriptsAdicionales
{
    @Scripts.Render("~/bundles/jqueryval")
}

Clase07 - 11/slnVentas/App.UI.Web.MVC/Views/Categoria/IndexListado.cshtml
@model IEnumerable<App.Entities.Base.Categoria>

<table class="table table-hover mb-0">
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Descripción</th>
            <th></th>
        </tr>
    </thead>

    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Nombre</td>
            <td>@item.Descripcion</td>
            <td>
                <a href=@Url.Action("Edit", new { @id = item.CategoriaID }) class="btn btn-warning btn-sm">
                    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                </a>
            </td>
        </tr>
    }

</table>